server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://223.93.139.200:10010/sg_demo?characterEncoding=utf-8&useSSL=false
    username: root
    password: hzzl2016
  http:
    encoding:
      charset: utf-8
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    #       ddl-auto: create 每次都新建表 update 更新数据 validate 验证标结构属性是否一致
    show-sql: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5